// todo give types to category_channel_mapping such that category should be a element of categories
export const CATEGORY_CHANNEL_MAPPING = [
	{
		category: "tools",
		channels: [
			"audio-tools",
			"career-tools",
			"developer-tools",
			"discord-tools",
			"educational-tools",
			"file-tools",
			"facebook-tools",
			"gaming-tools",
			"general-tools",
			"image-tools",
			"internet-tools",
			"reddit-tools",
			"search-tools",
			"system-tools",
			"telegram-tools",
			"text-tools",
			"twitch-tools",
			"twitter-tools",
			"url-tools",
			"video-tools",
			"youtube-tools",
		],
	},
	{
		category: "miscellaneous",
		channels: [
			"browser-games",
			"cooking",
			"extensions",
			"fonts",
			"fun-sites",
			"health",
			"indexes",
			"maps",
			"media-databases",
			"news",
			"non-english",
			"piracy-discussion",
			"request-media",
			"subtitles",
		],
	},
	{
		category: "reading",
		channels: [
			"audiobooks",
			"comics",
			"ebook-readers",
			"educational",
			"general",
			"light-novels",
			"manga",
			"magazines",
			"religion-esoteric",
			"newspapers",
		],
	},
	{
		category: "android_ios",
		channels: [
			"android-adblocking",
			"android-audio",
			"android-emulators",
			"android-general",
			"android-privacy",
			"android-reading",
			"android-torrenting",
			"android-video",
			"ios-adblocking",
			"ios-audio",
			"ios-general",
			"ios-jailbreaking",
			"ios-privacy",
			"ios-torrenting",
			"ios-reading",
			"ios-video",
		],
	},
	{
		category: "downloading",
		channels: [
			"anime",
			"arcade-retro",
			"educational",
			"emulators-roms",
			"games",
			"general",
			"movies-tv",
			"music",
			"software",
			"usenet",
		],
	},
	{
		category: "torrenting",
		channels: [
			"anime",
			"educational",
			"games",
			"general",
			"movies-tv",
			"music",
			"torrent-clients",
		],
	},
	{
		category: "linux_macos",
		channels: [
			"linux-adblock-privacy",
			"linux-gaming",
			"linux-general",
			"linux-software",
			"mac-adblock-privacy",
			"mac-gaming",
			"mac-general",
			"mac-software",
		],
	},
	{
		category: "streaming",
		channels: [
			"ambient-relaxation",
			"anime",
			"educational",
			"movies-tv",
			"live-tv",
			"podcasts-radio",
			"music",
			"sports",
		],
	},
	{
		category: "adblock_privacy",
		channels: [
			"adblocking",
			"antivirus",
			"dns",
			"privacy",
			"proxies",
			"vpn",
		],
	},
] as const;

export const CATEGORIES = [
	"tools",
	"miscellaneous",
	"reading",
	"android_ios",
	"downloading",
	"torrenting",
	"linux_macos",
	"streaming",
	"adblock_privacy",
] as const;

export const REDDIT_CATEGORIES = [
	"adblock-vpn-privacy",
	"video",
	"audio",
	"games",
	"reading",
	"download",
	"torrent",
	"edu",
	"tools-misc",
	"misc",
	"android",
	"linux",
	"storage",
	"non-eng",
	"base64",
] as const;

// export const CATEGORIES = Object.freeze(
// 	CATEGORY_CHANNEL_MAPPING.map((item) => item.category)
// );
